version: "3.2"
services:
  php:
    build: './php/'
    volumes:
      - ./public_html/:/var/www/html/
  web:
    build: './apache/'
    depends_on:
      - php
      - db
    ports:
      - "8181:80"
    volumes:
      - ./public_html/:/var/www/html/
  db:
    image: mysql:5.7
    user: "root"
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=dbvote

  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - "8282:80"
    links:
      - db:db
    restart: always
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=rootpassword
    depends_on:
       - db
