version: "3.2"
services:
  php:
    build: './php/'
    networks:
      - belakang
    volumes:
      - ./public_html/:/var/www/html/
  web:
    build: './apache/'
    depends_on:
      - php
      - db
    networks:
      - depan
      - belakang
    ports:
      - "8181:80"
    volumes:
      - ./public_html/:/var/www/html/
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
        - "8282:80"
    environment:
        - PMA_ARBITRARY=1
    restart: always
    depends_on:
       - mysqldb
  db:
    image: mysql:5.6.40
    networks:
      - belakang
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
networks:
  depan:
  belakang:
